resource_group_name = "rg-webserver"
location            = "France Central"
vm_name             = "srv-web-linux"
admin_username      = "adminuser"
prefix              = "webvm"
ssh_public_key = "AAAAB3NzaC1yc2EAAAADAQABAAABAQC3v5Z"
