---
- name: Installer et configurer Active Directory Domain Services (AD DS)
  hosts: windows
  become: yes
  become_method: runas
  become_user: "{{ domain_admin_user }}"
  vars_files:
    - vault.yml  # Variables sensibles chiffrées avec Ansible Vault

  tasks:

    - name: Vérifier si la fonctionnalité AD DS est déjà installée
      win_feature:
        name: AD-Domain-Services
        state: present
      register: ad_feature_status

    - name: Afficher le statut de la fonctionnalité AD DS
      debug:
        var: ad_feature_status

    - name: Vérifier si le rôle AD DS est installé
      win_shell: |
        (Get-WindowsFeature -Name AD-Domain-Services).Installed
      register: ad_role_status
      ignore_errors: yes

    - name: Afficher le statut du rôle AD DS
      debug:
        var: ad_role_status

    - name: Vérifier la valeur de safe_mode_password
      debug:
        var: safe_mode_password

    - name: Configurer le premier contrôleur de domaine dans une nouvelle forêt
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ safe_mode_password }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        domain_type: forest
        state: domain_controller
      register: domain_status
      when: ad_role_status.stdout.strip() == "True"

    - name: Afficher le statut de la promotion en contrôleur de domaine
      debug:
        var: domain_status

    - name: Redémarrer le serveur après la promotion en contrôleur de domaine
      win_reboot:
        msg: "Redémarrage après promotion en DC"
      when: domain_status.changed

    - name: Attendre que la machine soit de nouveau disponible
      wait_for_connection:
        timeout: 300
        sleep: 15
      when: domain_status.changed
      register: wait_status
      ignore_errors: yes
      