---
- name: Installer Active Directory Domain Services (AD DS)
  hosts: ad_servers  # Groupe de serveurs AD dans votre inventaire Ansible
  become:
  vars:
    domain_name: "cyna.local"  # Remplacez par votre nom de domaine
    safe_mode_password: "Pa$$word1234!"  # Remplacez par un mot de passe de mode sans échec sécurisé

  tasks:

    - name: Vérifier si la fonctionnalité AD DS est déjà installée
      win_feature:
        name: AD-Domain-Services
        state: present
      register: ad_feature_status

    - name: Afficher le statut de la fonctionnalité AD DS
      debug:
        var: ad_feature_status

    - name: Vérifier si le rôle AD DS est installé
      win_shell: |
        (Get-WindowsFeature -Name AD-Domain-Services).Installed
      register: ad_role_status
      ignore_errors: yes

    - name: Afficher le statut du rôle AD DS
      debug:
        var: ad_role_status

    - name: Vérifier la valeur de safe_mode_password
      debug:
        var: safe_mode_password

    - name: Configurer le premier contrôleur de domaine dans une nouvelle forêt
      win_domain:
        safe_mode_administrator_password: "{{ safe_mode_password | b64encode }}"
        domain_name: "{{ domain_name }}"
        domain_type: create 
        state: present
      when: not ad_feature_status.changed

    - name: Redémarrer le serveur après la promotion en contrôleur de domaine
      win_reboot:
      when: not ad_feature_status.changed
