name: 'Terraform Azure Pipeline'

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    if: github.event.inputs.action == 'apply' || github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Generate SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
          echo "SSH_PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)" >> $GITHUB_ENV
          SSH_PRIVATE_KEY=$(base64 ~/.ssh/id_rsa | tr -d '\n')
          echo "SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: pipeline

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: pipeline

      - name: Terraform Validate
        run: terraform validate
        working-directory: pipeline

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: pipeline
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_ssh_public_key: ${{ env.SSH_PUBLIC_KEY }}

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -input=false -var-file="terraform.tfvars"
        working-directory: pipeline
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_ssh_public_key: ${{ env.SSH_PUBLIC_KEY }}

      - name: Get VM Public IP
        run: |
          VM_PUBLIC_IP=$(terraform -chdir=pipeline output -raw vm_public_ip -no-color | tr -d '\n')
          echo "VM_PUBLIC_IP=$VM_PUBLIC_IP" >> $GITHUB_ENV

      - name: Générer l'inventaire Ansible complet
        run: |
          echo "[web_server]" > inventory.ini
          echo "vm ansible_host=$VM_PUBLIC_IP ansible_user=adminuser ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3" >> inventory.ini

      - name: Afficher inventory.ini
        run: cat inventory.ini

      - name: Générer ansible.cfg
        run: |
          echo "[defaults]" > ansible.cfg
          echo "inventory = inventory.ini" >> ansible.cfg
          echo "host_key_checking = False" >> ansible.cfg
          echo "retry_files_enabled = False" >> ansible.cfg

      - name: Run Ansible Playbook
        run: |
          echo "${SSH_PRIVATE_KEY}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ansible-playbook -i inventory.ini -u adminuser --private-key ~/.ssh/id_rsa serveur_web_linux/deploy_ansible_httpd_config/install_httpd_fedora.yml
        env:
          VM_PUBLIC_IP: ${{ env.VM_PUBLIC_IP }}
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}

      - name: Nettoyage fichiers sensibles
        if: always()
        run: |
          rm -f inventory.ini ansible.cfg
          shred -u ~/.ssh/id_rsa ~/.ssh/id_rsa.pub


  destroy:
    if: github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest
    # needs: []

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: pipeline

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
        working-directory: pipeline
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
